{"version":3,"file":" tryToGetData_AXIOS.spec.js","sourceRoot":"","sources":["../../../../src/test/__test__/ tryToGetData_AXIOS.spec.ts"],"names":[],"mappings":";;;AAAA,4DAA2D;AAC3D,8EAAuE;AAEvE,IAAI,CAAC,4BAA4B,EAAE,UAAM,IAAI;;;;;gBACrC,QAAQ,GAAG,mCAAa,CAAC;oBAC7B,GAAG,EAAE,OAAO;oBACZ,IAAI,EAAE,IAAI;oBACV,MAAM,EAAE,KAAK;oBACb,OAAO,EAAE,EAAE,QAAQ,EAAE,SAAS,EAAE,aAAa,EAAE,KAAK,EAAE;iBACvD,CAAC,CAAC;;;;gBAED,KAAA,MAAM,CAAA;gBAAC,qBAAM,QAAQ,CAAC,uBAAU,CAAC,EAAA;;gBAAjC,kBAAO,SAA0B,EAAC,CAAC,OAAO,EAAE,CAAC;;;;;;gBAI/C,iBAAiB;gBACjB,IAAI,EAAE,CAAC;;;;KACR,CAAC,CAAC","sourcesContent":["import { _logErrors } from '../../private/core/_logErrors';\nimport { _tryToGetData } from '../../private/core/_tryToGetData_AXIOS';\n\ntest('should ERROR _tryToGetData', async done => {\n  const response = _tryToGetData({\n    url: 'ERROR',\n    data: null,\n    method: 'get',\n    headers: { location: '1234567', Authorization: 'str' },\n  });\n  try {\n    expect(await response(_logErrors)).toThrow();\n  } catch (_) {\n    //\n  }\n  // console.log();\n  done();\n});\n"]}